name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme Instructions -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12' || xcodebuild -scheme Instructions -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 12'
